<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/3__select_feature.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [44]:
import numpy as np
import pandas as pd

from google.colab import drive
import os

In [45]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [46]:
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv')

In [47]:
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv')

In [48]:
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv')

In [49]:
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv')

# Loading the Data and Selecting the Features

In [31]:
# loan_data_inputs_train = pd.read_csv('loan_data_inputs_train.csv', index_col = 0)
# loan_data_targets_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0, header = None)
# loan_data_inputs_test = pd.read_csv('loan_data_inputs_test.csv', index_col = 0)
# loan_data_targets_test = pd.read_csv('loan_data_targets_test.csv', index_col = 0, header = None)

### Explore Data

In [50]:
pd.set_option('display.max_info_rows', 300)
loan_data_inputs_train.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_missing,emp_length_int,term_int,earliest_cr_line_date,months_since_earliest_cr_line,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w,home_ownership:RENT_OTHER_NONE_ANY,addr_state:ND,addr_state:ND_NE_IA_NV_FL_HI_AL,addr_state:OK_LA_NC_NM_MO_VA_NJ,addr_state:MD_TN_AZ_PA_MI,addr_state:DE_AR,addr_state:UT_MN_OH_IN_GA_ RI_WA,addr_state:OR_KY_MA,addr_state:MT_MS_SD,addr_state:WI_IL_CT_AK,addr_state:CO_SC,addr_state:KS_NH_WV_VT_ID,addr_state:WY_DC_ME,purpose:educ__sm_b__wedd__ren_en__mov__house,purpose:oth__med__vacation,purpose:major_purch__car__home_impr,term:36,term:60,emp_length:0,emp_length:1,emp_length:2-4,emp_length:5-6,emp_length:7-9,emp_length:10,mths_since_issue_d_factor,mths_since_issue_d:<38,mths_since_issue_d:38-39,mths_since_issue_d:40-41,mths_since_issue_d:42-48,mths_since_issue_d:49-52,mths_since_issue_d:53-64,mths_since_issue_d:65-84,mths_since_issue_d:>84,int_rate_factor,int_rate:<9.548,int_rate:9.548-12.025,int_rate:12.025-15.74,int_rate:15.74-20.281,int_rate:>20.281,funded_amnt_factor,mths_since_earliest_cr_line_factor,mths_since_earliest_cr_line:<140,mths_since_earliest_cr_line:141-164,mths_since_earliest_cr_line:165-247,mths_since_earliest_cr_line:248-270,mths_since_earliest_cr_line:271-352,mths_since_earliest_cr_line:>352,delinq_2yrs:0,delinq_2yrs:1-3,delinq_2yrs:4-16,delinq_2yrs:>=17,inq_last_6mths:0,inq_last_6mths:1-2,inq_last_6mths:3-6,inq_last_6mths:>6,open_acc:0,open_acc:1-3,open_acc:4-12,open_acc:13-17,open_acc:18-22,open_acc:23-25,open_acc:26-30,open_acc:>=31,pub_rec:0-2,pub_rec:3-4,pub_rec:>=5,total_acc_factor,total_acc:0-15,total_acc:16-70,total_acc:71-90,total_acc:>90,acc_now_delinq:0,acc_now_delinq:>=1,total_rev_hi_lim_factor,total_rev_hi_lim:<=5K,total_rev_hi_lim:5K-10K,total_rev_hi_lim:10K-20K,total_rev_hi_lim:20K-30K,total_rev_hi_lim:30K-40K,total_rev_hi_lim:40K-55K,total_rev_hi_lim:55K-95K,installment_factor,installment:<=800,installment:801-1100,installment:1101-1250,installment:>1250,annual_inc_factor,annual_inc:<20K,annual_inc:20K-30K,annual_inc:30K-40K,annual_inc:40K-50K,annual_inc:50K-60K,annual_inc:60K-70K,annual_inc:70K-80K,annual_inc:80K-90K,annual_inc:90K-100K,annual_inc:100K-120K,annual_inc:120K-140K,annual_inc:>140K,mths_since_last_delinq:Missing,mths_since_last_delinq:0-3,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,dti_factor,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
0,292984,29074404,31607606,11250,11250,11250.0,60 months,16.99,279.54,D,D3,firefighter,8 years,MORTGAGE,74300.0,Not Verified,Oct-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,363xx,AL,21.24,0.0,NaN,2.0,NaN,NaN,13.0,0.0,23031,59.4,48.0,w,9255.89,9255.89,4193.10,4193.10,1994.11,2198.99,0.000000,0.00,0.00,Jan-16,279.54,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,121337.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38800.0,NaN,NaN,NaN,0,8.0,60,1993-07-01,293.0,2014-10-01,38,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,"(37.8, 39.6]",0,1,0,0,0,0,0,0,"(16.978, 17.391]",0,0,0,1,0,"(10850.0, 11540.0]","(290.0, 301.6]",0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,"(46.8, 49.92]",0,1,0,0,1,0,"(34999.996, 39999.996]",0,0,0,0,1,0,0,"(266.648, 294.534]",1,0,0,0,"(-5602.104, 76877.04]",0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,"(21.195, 21.595]",0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
1,57793,9026077,10838105,8000,8000,8000.0,36 months,18.55,291.44,D,D2,manager,7 years,RENT,32000.0,Not Verified,Nov-13,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,credit cards,124xx,NY,29.41,0.0,NaN,2.0,NaN,NaN,9.0,0.0,10746,82.0,16.0,w,2927.04,2927.04,7300.04,7300.04,5072.96,2227.08,0.000000,0.00,0.00,Jan-16,291.44,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,29746.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN,0,7.0,36,2007-05-01,127.0,2013-11-01,49,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,"(48.6, 50.4]",0,0,0,0,1,0,0,0,"(18.217, 18.63]",0,0,0,1,0,"(7400.0, 8090.0]","(116.0, 127.6]",1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,"(15.6, 18.72]",0,1,0,0,1,0,"(9999.999, 14999.998]",0,0,1,0,0,0,0,"(266.648, 294.534]",1,0,0,0,"(-5602.104, 76877.04]",0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,"(29.193, 29.593]",0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
2,140700,4865088,6157358,6000,6000,6000.0,36 months,10.16,194.06,B,B1,American Westbrook Insurance Services,10+ years,MORTGAGE,85000.0,Not Verified,May-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,601xx,IL,3.85,0.0,NaN,3.0,45.0,NaN,10.0,0.0,9280,53.0,37.0,f,0.00,0.00,6051.30,6051.30,6000.00,51.30,0.000000,0.00,0.00,Jun-13,6051.46,NaN,Jan-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,144.0,134379.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17500.0,NaN,NaN,NaN,0,10.0,36,1991-05-01,319.0,2013-05-01,55,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,"(54.0, 55.8]",0,0,0,0,0,1,0,0,"(9.961, 10.374]",0,1,0,0,0,"(5330.0, 6020.0]","(313.2, 324.8]",0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,"(34.32, 37.44]",0,1,0,0,1,0,"(14999.998, 19999.998]",0,0,1,0,0,0,0,"(182.988, 210.875]",1,0,0,0,"(76877.04, 151858.08]",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,"(3.599, 3.999]",0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,297571,28764454,31297687,8000,8000,8000.0,36 months,9.17,255.04,B,B1,CFO,10+ years,MORTGAGE,100000.0,Source Verified,Oct-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,891xx,NV,20.35,0.0,NaN,1.0,44.0,NaN,9.0,0.0,2092,30.8,24.0,w,4930.54,4930.54,3825.60,3825.60,3069.46,756.14,0.000000,0.00,0.00,Jan-16,255.04,Feb-16,Jan-16,0.0,58.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,53777.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6800.0,NaN,NaN,NaN,0,10.0,36,2002-08-01,184.0,2014-10-01,38,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,"(37.8, 39.6]",0,1,0,0,0,0,0,0,"(9.135, 9.548]",1,0,0,0,0,"(7400.0, 8090.0]","(174.0, 185.6]",0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,"(21.84, 24.96]",0,1,0,0,1,0,"(5000.0, 9999.999]",0,1,0,0,0,0,0,"(238.761, 266.648]",1,0,0,0,"(76877.04, 151858.08]",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,"(19.995, 20.395]",0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
4,5264,985083,1208540,5000,5000,5000.0,36 months,11.71,165.38,B,B3,G4S Secure Solutions USA Inc.,3 years,RENT,21120.0,Not Verified,Oct-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Pay It Off,339xx,FL,19.15,0.0,NaN,0.0,NaN,NaN,6.0,0.0,2073,76.8,10.0,f,0.00,0.00,1725.01,1725.01,1087.82,397.64,14.980044,224.57,2.16,Jul-12,345.76,NaN,Dec-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN,0,3.0,36,2006-08-01,136.0,2011-10-01,74,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,"(73.8, 75.6]",0,0,0,0,0,0,1,0,"(11.612, 12.025]",0,1,0,0,0,"(4640.0, 5330.0]","(127.6, 139.2]",1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,"(9.36, 12.48]",1,0,0,0,1,0,"(5000.0, 9999.999]",1,0,0,0,0,0,0,"(155.102, 182.988]",1,0,0,0,"(-5602.104, 76877.04]",0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,"(18.795, 19.195]",0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0

In [51]:
loan_data_targets_train.head()

   good_bad
0         1
1         1
2         1
3         1
4         0

In [52]:
loan_data_inputs_train.shape

(373028, 330)

In [53]:
loan_data_targets_train.shape

(373028, 1)

In [54]:
loan_data_inputs_test.shape

(93252, 330)

In [55]:
loan_data_targets_test.shape

(93252, 1)

In [56]:
for i, col in enumerate(loan_data_inputs_train.columns, 1):
    print(f"{i}. {col}")

1. Unnamed: 0
2. id
3. member_id
4. loan_amnt
5. funded_amnt
6. funded_amnt_inv
7. term
8. int_rate
9. installment
10. grade
11. sub_grade
12. emp_title
13. emp_length
14. home_ownership
15. annual_inc
16. verification_status
17. issue_d
18. loan_status
19. pymnt_plan
20. url
21. desc
22. purpose
23. title
24. zip_code
25. addr_state
26. dti
27. delinq_2yrs
28. earliest_cr_line
29. inq_last_6mths
30. mths_since_last_delinq
31. mths_since_last_record
32. open_acc
33. pub_rec
34. revol_bal
35. revol_util
36. total_acc
37. initial_list_status
38. out_prncp
39. out_prncp_inv
40. total_pymnt
41. total_pymnt_inv
42. total_rec_prncp
43. total_rec_int
44. total_rec_late_fee
45. recoveries
46. collection_recovery_fee
47. last_pymnt_d
48. last_pymnt_amnt
49. next_pymnt_d
50. last_credit_pull_d
51. collections_12_mths_ex_med
52. mths_since_last_major_derog
53. policy_code
54. application_type
55. annual_inc_joint
56. dti_joint
57. verification_status_joint
58. acc_now_delinq
59. tot_coll_amt
60. tot_cur_bal
61. open_acc_6m
62. open_il_6m
63. open_il_12m
64. open_il_24m
65. mths_since_rcnt_il
66. total_bal_il
67. il_util
68. open_rv_12m
69. open_rv_24m
70. max_bal_bc
71. all_util
72. total_rev_hi_lim
73. inq_fi
74. total_cu_tl
75. inq_last_12m
76. emp_length_missing
77. emp_length_int
78. term_int
79. earliest_cr_line_date
80. months_since_earliest_cr_line
81. issue_d_date
82. mths_since_issue_d
83. grade:A
84. grade:B
85. grade:C
86. grade:D
87. grade:E
88. grade:F
89. grade:G
90. sub_grade:A1
91. sub_grade:A2
92. sub_grade:A3
93. sub_grade:A4
94. sub_grade:A5
95. sub_grade:B1
96. sub_grade:B2
97. sub_grade:B3
98. sub_grade:B4
99. sub_grade:B5
100. sub_grade:C1
101. sub_grade:C2
102. sub_grade:C3
103. sub_grade:C4
104. sub_grade:C5
105. sub_grade:D1
106. sub_grade:D2
107. sub_grade:D3
108. sub_grade:D4
109. sub_grade:D5
110. sub_grade:E1
111. sub_grade:E2
112. sub_grade:E3
113. sub_grade:E4
114. sub_grade:E5
115. sub_grade:F1
116. sub_grade:F2
117. sub_grade:F3
118. sub_grade:F4
119. sub_grade:F5
120. sub_grade:G1
121. sub_grade:G2
122. sub_grade:G3
123. sub_grade:G4
124. sub_grade:G5
125. home_ownership:ANY
126. home_ownership:MORTGAGE
127. home_ownership:NONE
128. home_ownership:OTHER
129. home_ownership:OWN
130. home_ownership:RENT
131. verification_status:Not Verified
132. verification_status:Source Verified
133. verification_status:Verified
134. loan_status:Charged Off
135. loan_status:Current
136. loan_status:Default
137. loan_status:Does not meet the credit policy. Status:Charged Off
138. loan_status:Does not meet the credit policy. Status:Fully Paid
139. loan_status:Fully Paid
140. loan_status:In Grace Period
141. loan_status:Late (16-30 days)
142. loan_status:Late (31-120 days)
143. purpose:car
144. purpose:credit_card
145. purpose:debt_consolidation
146. purpose:educational
147. purpose:home_improvement
148. purpose:house
149. purpose:major_purchase
150. purpose:medical
151. purpose:moving
152. purpose:other
153. purpose:renewable_energy
154. purpose:small_business
155. purpose:vacation
156. purpose:wedding
157. addr_state:AK
158. addr_state:AL
159. addr_state:AR
160. addr_state:AZ
161. addr_state:CA
162. addr_state:CO
163. addr_state:CT
164. addr_state:DC
165. addr_state:DE
166. addr_state:FL
167. addr_state:GA
168. addr_state:HI
169. addr_state:IA
170. addr_state:ID
171. addr_state:IL
172. addr_state:IN
173. addr_state:KS
174. addr_state:KY
175. addr_state:LA
176. addr_state:MA
177. addr_state:MD
178. addr_state:ME
179. addr_state:MI
180. addr_state:MN
181. addr_state:MO
182. addr_state:MS
183. addr_state:MT
184. addr_state:NC
185. addr_state:NE
186. addr_state:NH
187. addr_state:NJ
188. addr_state:NM
189. addr_state:NV
190. addr_state:NY
191. addr_state:OH
192. addr_state:OK
193. addr_state:OR
194. addr_state:PA
195. addr_state:RI
196. addr_state:SC
197. addr_state:SD
198. addr_state:TN
199. addr_state:TX
200. addr_state:UT
201. addr_state:VA
202. addr_state:VT
203. addr_state:WA
204. addr_state:WI
205. addr_state:WV
206. addr_state:WY
207. initial_list_status:f
208. initial_list_status:w
209. home_ownership:RENT_OTHER_NONE_ANY
210. addr_state:ND
211. addr_state:ND_NE_IA_NV_FL_HI_AL
212. addr_state:OK_LA_NC_NM_MO_VA_NJ
213. addr_state:MD_TN_AZ_PA_MI
214. addr_state:DE_AR
215. addr_state:UT_MN_OH_IN_GA_ RI_WA
216. addr_state:OR_KY_MA
217. addr_state:MT_MS_SD
218. addr_state:WI_IL_CT_AK
219. addr_state:CO_SC
220. addr_state:KS_NH_WV_VT_ID
221. addr_state:WY_DC_ME
222. purpose:educ__sm_b__wedd__ren_en__mov__house
223. purpose:oth__med__vacation
224. purpose:major_purch__car__home_impr
225. term:36
226. term:60
227. emp_length:0
228. emp_length:1
229. emp_length:2-4
230. emp_length:5-6
231. emp_length:7-9
232. emp_length:10
233. mths_since_issue_d_factor
234. mths_since_issue_d:<38
235. mths_since_issue_d:38-39
236. mths_since_issue_d:40-41
237. mths_since_issue_d:42-48
238. mths_since_issue_d:49-52
239. mths_since_issue_d:53-64
240. mths_since_issue_d:65-84
241. mths_since_issue_d:>84
242. int_rate_factor
243. int_rate:<9.548
244. int_rate:9.548-12.025
245. int_rate:12.025-15.74
246. int_rate:15.74-20.281
247. int_rate:>20.281
248. funded_amnt_factor
249. mths_since_earliest_cr_line_factor
250. mths_since_earliest_cr_line:<140
251. mths_since_earliest_cr_line:141-164
252. mths_since_earliest_cr_line:165-247
253. mths_since_earliest_cr_line:248-270
254. mths_since_earliest_cr_line:271-352
255. mths_since_earliest_cr_line:>352
256. delinq_2yrs:0
257. delinq_2yrs:1-3
258. delinq_2yrs:4-16
259. delinq_2yrs:>=17
260. inq_last_6mths:0
261. inq_last_6mths:1-2
262. inq_last_6mths:3-6
263. inq_last_6mths:>6
264. open_acc:0
265. open_acc:1-3
266. open_acc:4-12
267. open_acc:13-17
268. open_acc:18-22
269. open_acc:23-25
270. open_acc:26-30
271. open_acc:>=31
272. pub_rec:0-2
273. pub_rec:3-4
274. pub_rec:>=5
275. total_acc_factor
276. total_acc:0-15
277. total_acc:16-70
278. total_acc:71-90
279. total_acc:>90
280. acc_now_delinq:0
281. acc_now_delinq:>=1
282. total_rev_hi_lim_factor
283. total_rev_hi_lim:<=5K
284. total_rev_hi_lim:5K-10K
285. total_rev_hi_lim:10K-20K
286. total_rev_hi_lim:20K-30K
287. total_rev_hi_lim:30K-40K
288. total_rev_hi_lim:40K-55K
289. total_rev_hi_lim:55K-95K
290. installment_factor
291. installment:<=800
292. installment:801-1100
293. installment:1101-1250
294. installment:>1250
295. annual_inc_factor
296. annual_inc:<20K
297. annual_inc:20K-30K
298. annual_inc:30K-40K
299. annual_inc:40K-50K
300. annual_inc:50K-60K
301. annual_inc:60K-70K
302. annual_inc:70K-80K
303. annual_inc:80K-90K
304. annual_inc:90K-100K
305. annual_inc:100K-120K
306. annual_inc:120K-140K
307. annual_inc:>140K
308. mths_since_last_delinq:Missing
309. mths_since_last_delinq:0-3
310. mths_since_last_delinq:4-30
311. mths_since_last_delinq:31-56
312. mths_since_last_delinq:>=57
313. dti_factor
314. dti:<=1.4
315. dti:1.4-3.5
316. dti:3.5-7.7
317. dti:7.7-10.5
318. dti:10.5-16.1
319. dti:16.1-20.3
320. dti:20.3-21.7
321. dti:21.7-22.4
322. dti:22.4-35
323. dti:>35
324. mths_since_last_record:Missing
325. mths_since_last_record:0-2
326. mths_since_last_record:3-20
327. mths_since_last_record:21-31
328. mths_since_last_record:32-80
329. mths_since_last_record:81-86
330. mths_since_last_record:>86

### Selecting the Features

In [57]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',

'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',

'addr_state:ND',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:OK_LA_NC_NM_MO_VA_NJ',
'addr_state:MD_TN_AZ_PA_MI',
'addr_state:DE_AR',
'addr_state:UT_MN_OH_IN_GA_ RI_WA',
'addr_state:OR_KY_MA',
'addr_state:MT_MS_SD',
'addr_state:WI_IL_CT_AK',
'addr_state:CO_SC',
'addr_state:KS_NH_WV_VT_ID',
'addr_state:WY_DC_ME',

'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',

'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',

'initial_list_status:f',
'initial_list_status:w',

'term:36',
'term:60',

'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',

'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',

'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',

'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',


'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:4-16',
'delinq_2yrs:>=17',


'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',


'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',

'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',

'total_acc:0-15',
'total_acc:16-70',
'total_acc:71-90',
'total_acc:>90',

'acc_now_delinq:0',
'acc_now_delinq:>=1',

'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',



'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',

'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',


'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',

'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',

]]

In [58]:
# Here we store the names of the reference category dummy variables in a list.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:0',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:0-15',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [59]:
pd.set_option('display.max_info_rows', 100)
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
# From the dataframe with input variables, we drop the variables with variable names in the list with reference categories.
inputs_train.sample(100)

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:ND,addr_state:OK_LA_NC_NM_MO_VA_NJ,addr_state:MD_TN_AZ_PA_MI,addr_state:DE_AR,addr_state:UT_MN_OH_IN_GA_ RI_WA,addr_state:OR_KY_MA,addr_state:MT_MS_SD,addr_state:WI_IL_CT_AK,addr_state:CO_SC,addr_state:KS_NH_WV_VT_ID,addr_state:WY_DC_ME,verification_status:Not Verified,verification_status:Source Verified,purpose:credit_card,purpose:debt_consolidation,purpose:oth__med__vacation,purpose:major_purch__car__home_impr,initial_list_status:w,term:36,emp_length:1,emp_length:2-4,emp_length:5-6,emp_length:7-9,emp_length:10,mths_since_issue_d:<38,mths_since_issue_d:38-39,mths_since_issue_d:40-41,mths_since_issue_d:42-48,mths_since_issue_d:49-52,mths_since_issue_d:53-64,mths_since_issue_d:65-84,int_rate:<9.548,int_rate:9.548-12.025,int_rate:12.025-15.74,int_rate:15.74-20.281,mths_since_earliest_cr_line:141-164,mths_since_earliest_cr_line:165-247,mths_since_earliest_cr_line:248-270,mths_since_earliest_cr_line:271-352,mths_since_earliest_cr_line:>352,delinq_2yrs:1-3,delinq_2yrs:4-16,delinq_2yrs:>=17,inq_last_6mths:0,inq_last_6mths:1-2,inq_last_6mths:3-6,open_acc:1-3,open_acc:4-12,open_acc:13-17,open_acc:18-22,open_acc:23-25,open_acc:26-30,open_acc:>=31,pub_rec:3-4,pub_rec:>=5,total_acc:16-70,total_acc:71-90,total_acc:>90,acc_now_delinq:>=1,total_rev_hi_lim:5K-10K,total_rev_hi_lim:10K-20K,total_rev_hi_lim:20K-30K,total_rev_hi_lim:30K-40K,total_rev_hi_lim:40K-55K,total_rev_hi_lim:55K-95K,annual_inc:20K-30K,annual_inc:30K-40K,annual_inc:40K-50K,annual_inc:50K-60K,annual_inc:60K-70K,annual_inc:70K-80K,annual_inc:80K-90K,annual_inc:90K-100K,annual_inc:100K-120K,annual_inc:120K-140K,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
338168,False,False,False,False,True,False,False,False,0,0,0,0,0,0,0,0,0,0,0,False,True,False,True,0,0,True,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0
263237,True,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,True,False,False,True,0,0,True,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
287135,False,True,False,False,False,False,False,True,0,0,0,0,0,1,0,0,0,0,0,False,True,False,True,0,0,True,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0
37794,True,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,True,False,True,False,0,0,True,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
95992,False,True,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,False,False,True,False,0,0,False,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197275,False,True,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,False,False,False,True,0,0,False,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
65283,False,True,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,False,False,True,False,0,0,False,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
224213,False,False,True,False,False,False,False,False,0,0,0,0,1,0,0,0,0,0,0,False,True,True,False,0,0,True,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
224020,False,False,False,False,False,True,True,False,0,0,1,0,0,0,0,0,0,0,0,False,False,False,True,0,0,False,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
360802,False,False,True,False,False,False,False,True,0,0,0,0,0,0,0,0,0,0,0,False,False,True,False,0,0,False,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0