<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/notebooks/5_Monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import os

#from google.colab import data_table
#data_table.enable_dataframe_formatter()

from google.colab import data_table
data_table.disable_dataframe_formatter()

# unbegrenzte Zeilen und Spalten anzeigen
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [4]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Mounted at /content/drive

In [5]:
# Import Train and Test Data.
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv', index_col = 0)
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv', index_col = 0,)
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv', index_col = 0)
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv', index_col = 0, header = None)

In [6]:
loan_data_targets_train.head()

        good_bad
427211         1
206088         1
136020         1
412305         1
36159          0

In [40]:
loan_data_backup = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_2015.csv')

/tmp/ipython-input-3262726154.py:1: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_2015.csv')

In [41]:
loan_data_backup.shape

(421094, 74)

In [42]:
loan_data = loan_data_backup.copy()

In [49]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,10+ years,MORTGAGE,128000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,200xx,DC,6.46,0.0,Feb-90,0.0,46.0,NaN,17.0,0.0,14277,27.4,46.0,w,35000.0,35000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,56.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,321.0,146867.0,1.0,11.0,0.0,0.0,28.0,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0
1,68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,< 1 year,MORTGAGE,100000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,462xx,IN,7.28,0.0,Jul-01,0.0,NaN,NaN,15.0,0.0,7158,26.7,24.0,w,8650.0,8650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,165450.0,0.0,1.0,1.0,1.0,11.0,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0
2,67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,5 years,RENT,35000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,672xx,KS,15.22,2.0,Jul-11,0.0,18.0,NaN,6.0,0.0,1058,24.6,6.0,w,4225.0,4225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4888.0,0.0,1.0,0.0,0.0,47.0,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0
3,68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0.0,Dec-98,1.0,NaN,NaN,10.0,0.0,5812,40.9,23.0,w,10000.0,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,41166.0,1.0,3.0,0.0,2.0,13.0,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0
4,68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-00,0.0,NaN,NaN,6.0,0.0,7869,56.2,18.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Dec-15,0.0,NaN,1,JOINT,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0

In [50]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
dtypes: float64(45), int64(6), object(23)
memory usage: 237.7+ MB

# Population Stability Index: Preprocessing

### >>> The code from here to the other line starting with '>>>' is copied from the Data Preparation notebook, with minor adjustments. We have to perform the exact same data preprocessing, fine-classing, and coarse classing on the new data, in order to be able to calculate statistics for the exact same variables to the ones we used for training and testing the PD model.

### Preprocessing few continuous variables

## General Preprocessing

In [58]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '5 years', '3 years', '4 years', nan,
       '2 years', '8 years', '9 years', '1 year', '6 years', '7 years'],
      dtype=object)

In [59]:
# Ersetzt den String '10+ years' durch '10', um eine numerische Konvertierung zu ermöglichen.
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('10+ years', '10', regex=False)
# Ersetzt '< 1 year' durch '0', da dies einem Jahrzehnt von 0 Jahren entspricht.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0), regex=False)
# Ersetzt 'n/a' (Not Applicable) durch '0', da fehlende Werte hier als 0 Jahre betrachtet werden.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0), regex=False)
# Entfernt den String ' years' aus den Werten, um nur die numerischen Anteile zu behalten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '', regex=False)
# Entfernt den String ' year' (Singular) aus den Werten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '', regex=False)

In [60]:
type(loan_data['emp_length_int'][0])

str

In [61]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'], errors='coerce')

In [16]:
loan_data['emp_length_int'].head()

0    10.0
1     0.0
2     5.0
3    10.0
4    10.0
Name: emp_length_int, dtype: float64

In [62]:
loan_data['emp_length_int'].dtype

dtype('float64')

In [63]:
type(loan_data['emp_length_int'][0])

numpy.float64

Earliest credit line

In [64]:
loan_data['earliest_cr_line'].head()

0    Feb-90
1    Jul-01
2    Jul-11
3    Dec-98
4    Aug-00
Name: earliest_cr_line, dtype: object

In [65]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

In [66]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [76]:
pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date'].head(1)

0   10530 days
Name: earliest_cr_line_date, dtype: timedelta64[ns]

In [68]:
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date']) / np.timedelta64(1, 'D')) / 30.44)

In [33]:
# Zeigt deskriptive Statistiken für die Spalte 'mths_since_earliest_cr_line' an.
# Dies gibt uns einen Überblick über die Verteilung und mögliche Probleme (z.B. negative Werte).
loan_data['mths_since_earliest_cr_line'].describe()

count    421094.000000
mean        239.354876
std          98.123989
min        -600.000000
25%         179.000000
50%         224.000000
75%         289.000000
max         599.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [34]:
# Der Kommentar besagt, dass Daten aus 1969 oder früher falsch konvertiert wurden
# (z.B. 1969 wurde zu 2069) und dadurch negative Differenzen berechnet wurden.
# Es gibt 2303 solche Werte, die das Problem belegen.
# Dieser Code filtert den DataFrame, um die Zeilen anzuzeigen, bei denen 'mths_since_earliest_cr_line' negativ ist.
# Dies hilft, die betroffenen Einträge zu identifizieren.
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
254              Jan-57            2057-01-01                       -457.0
618              Aug-64            2064-08-01                       -548.0
648              Jul-68            2068-07-01                       -595.0
1808             Jan-65            2065-01-01                       -553.0
2583             Sep-64            2064-09-01                       -549.0
3040             May-66            2066-05-01                       -569.0
3250             Jul-68            2068-07-01                       -595.0
4877             Apr-65            2065-04-01                       -556.0
5031             Sep-62            2062-09-01                       -525.0
5560             Apr-68            2068-04-01                       -592.0
6039             Nov-66            2066-11-01                       -575.0
7063             Jul-65            2065-07-01                       -559.0
7119             Jan-68            2068-01-01                       -589.0
7583             Sep-65            2065-09-01                       -561.0
7791             Nov-65            2065-11-01                       -563.0
8285             Jan-60            2060-01-01                       -493.0
8667             Aug-67            2067-08-01                       -584.0
8895             Jan-67            2067-01-01                       -577.0
9639             Sep-63            2063-09-01                       -537.0
10032            Nov-65            2065-11-01                       -563.0
10313            Feb-68            2068-02-01                       -590.0
11311            Dec-65            2065-12-01                       -564.0
11374            Jan-63            2063-01-01                       -529.0
11476            Dec-62            2062-12-01                       -528.0
11725            Jan-64            2064-01-01                       -541.0
11826            Jul-68            2068-07-01                       -595.0
13053            Apr-66            2066-04-01                       -568.0
13284            Oct-68            2068-10-01                       -598.0
13705            Mar-68            2068-03-01                       -591.0
13727            Dec-66            2066-12-01                       -576.0
14372            May-67            2067-05-01                       -581.0
15107            Oct-66            2066-10-01                       -574.0
15888            Jan-60            2060-01-01                       -493.0
16165            Jan-59            2059-01-01                       -481.0
16524            Nov-68            2068-11-01                       -599.0
16732            Jan-68            2068-01-01                       -589.0
17065            Feb-65            2065-02-01                       -554.0
17192            Jan-59            2059-01-01                       -481.0
17443            Dec-61            2061-12-01                       -516.0
18016            May-67            2067-05-01                       -581.0
18097            Aug-67            2067-08-01                       -584.0
18252            Apr-66            2066-04-01                       -568.0
18319            Jun-68            2068-06-01                       -594.0
18548            Jan-61            2061-01-01                       -505.0
18724            Aug-62            2062-08-01                       -524.0
18805            Jul-68            2068-07-01                       -595.0
18876            Jun-68            2068-06-01                       -594.0
19376            Dec-62            2062-12-01                       -528.0
19937            May-61            2061-05-01                       -509.0
20002            Jan-67            2067-01-01                       -577.0
20195            Jun-68            2068-06-01                       -594.0
20808            Dec-58            2058-12-01                       -480.0
21195            Mar-67            2067-03-01                       -579.0
21586            Jan-59            2059-01-01                       -481.0
21634            Mar-63            2063-03-01                       -531.0
21844            Jan-61            2061-01-01                       -505.0
22196            Jul-63            2063-07-01                       -535.0
22341            Jul-68            2068-07-01                       -595.0
22422            Apr-67            2067-04-01                       -580.0
22873            Dec-64            2064-12-01                       -552.0
23004            Apr-67            2067-04-01                       -580.0
23046            Jan-68            2068-01-01                       -589.0
23237            Oct-68            2068-10-01                       -598.0
23735            Nov-65            2065-11-01                       -563.0
23854            Oct-58            2058-10-01                       -478.0
23972            Feb-68            2068-02-01                       -590.0
24093            Dec-68            2068-12-01                       -600.0
24575            Jan-67            2067-01-01                       -577.0
24658            Jan-67            2067-01-01                       -577.0
25081            Mar-67            2067-03-01                       -579.0
25285            Jan-67            2067-01-01                       -577.0
25444            Feb-59            2059-02-01                       -482.0
25547            Sep-66            2066-09-01                       -573.0
25560            Aug-68            2068-08-01                       -596.0
25573            Dec-65            2065-12-01                       -564.0
25606            Jan-67            2067-01-01                       -577.0
25662            Aug-67            2067-08-01                       -584.0
25810            Oct-59            2059-10-01                       -490.0
25816            Jan-50            2050-01-01                       -373.0
25833            Jan-62            2062-01-01                       -517.0
26060            Oct-64            2064-10-01                       -550.0
26102            Jun-65            2065-06-01                       -558.0
26279            Oct-62            2062-10-01                       -526.0
26376            Feb-61            2061-02-01                       -506.0
27314            Jun-67            2067-06-01                       -582.0
27315            Jul-63            2063-07-01                       -535.0
27377            Nov-67            2067-11-01                       -587.0
27462            Sep-61            2061-09-01                       -513.0
27683            Oct-68            2068-10-01                       -598.0
27740            Dec-63            2063-12-01                       -540.0
27766            Nov-67            2067-11-01                       -587.0
28777            Dec-65            2065-12-01                       -564.0
28813            Mar-62            2062-03-01                       -519.0
30088            Jan-56            2056-01-01                       -445.0
30655            Jan-68            2068-01-01                       -589.0
30674            Jan-67            2067-01-01                       -577.0
30763            Dec-68            2068-12-01                       -600.0
31111            Jun-62            2062-06-01                       -522.0
31224            Nov-65            2065-11-01                       -563.0
31518            May-65            2065-05-01                       -557.0
32064            Apr-65            2065-04-01                       -556.0
32353            Jun-66            2066-06-01                       -570.0
32475            Jan-65            2065-01-01                       -553.0
33165            Jun-55            2055-06-01                       -438.0
33270            Jun-65            2065-06-01                       -558.0
33784            May-64            2064-05-01                       -545.0
34666            Dec-62            2062-12-01                       -528.0
35375            Feb-67            2067-02-01                       -578.0
35413            Jan-68            2068-01-01                       -589.0
35480            Nov-65            2065-11-01                       -563.0
35484            Sep-67            2067-09-01                       -585.0
35912            Dec-64            2064-12-01                       -552.0
36601            Jul-68            2068-07-01                       -595.0
37482            Aug-68            2068-08-01                       -596.0
38100            Aug-66            2066-08-01                       -572.0
38468            Feb-64            2064-02-01                       -542.0
38488            Jun-68            2068-06-01                       -594.0
39119            Jan-64            2064-01-01                       -541.0
39690            Dec-67            2067-12-01                       -588.0
39872            Jan-67            2067-01-01                       -577.0
40767            May-68            2068-05-01                       -593.0
42639            Jul-68            2068-07-01                       -595.0
42676            Jul-67            2067-07-01                       -583.0
42901            Nov-65            2065-11-01                       -563.0
43089            Mar-67            2067-03-01                       -579.0
43124            Dec-66            2066-12-01                       -576.0
43160            Jan-65            2065-01-01                       -553.0
43400            Jan-62            2062-01-01                       -517.0
43520            Jul-66            2066-07-01                       -571.0
43884            Jan-67            2067-01-01                       -577.0
44153            Sep-65            2065-09-01                       -561.0
44562            Nov-65            2065-11-01                       -563.0
44660            Feb-65            2065-02-01                       -554.0
44752            May-67            2067-05-01                       -581.0
45114            Jan-61            2061-01-01                       -505.0
45383            Jan-62            2062-01-01                       -517.0
45645            Jan-66            2066-01-01                       -565.0
46919            Aug-67            2067-08-01                       -584.0
46957            Jul-65            2065-07-01                       -559.0
47203            Sep-68            2068-09-01                       -597.0
47232            May-68            2068-05-01                       -593.0
47527            Dec-64            2064-12-01                       -552.0
47910            Jun-63            2063-06-01                       -534.0
48099            Jan-65            2065-01-01                       -553.0
49617            Oct-65            2065-10-01                       -562.0
49954            Sep-68            2068-09-01                       -597.0
50181            Sep-68            2068-09-01                       -597.0
50428            Oct-63            2063-10-01                       -538.0
51347            May-67            2067-05-01                       -581.0
51805            Aug-64            2064-08-01                       -548.0
51994            Oct-64            2064-10-01                       -550.0
53383            Aug-66            2066-08-01                       -572.0
53560            Apr-67            2067-04-01                       -580.0
53961            Nov-63            2063-11-01                       -539.0
54598            Jan-67            2067-01-01                       -577.0
54719            Mar-67            2067-03-01                       -579.0
55938            Jan-68            2068-01-01                       -589.0
56271            Apr-63            2063-04-01                       -532.0
57126            Jan-61            2061-01-01                       -505.0
57700            Aug-68            2068-08-01                       -596.0
57708            Apr-67            2067-04-01                       -580.0
57911            Oct-65            2065-10-01                       -562.0
58522            Nov-66            2066-11-01                       -575.0
59340            Aug-67            2067-08-01                       -584.0
60355            Feb-66            2066-02-01                       -566.0
60654            Jan-66            2066-01-01                       -565.0
60843            Jul-67            2067-07-01                       -583.0
61331            Dec-66            2066-12-01                       -576.0
61463            Jan-68            2068-01-01                       -589.0
61594            Oct-63            2063-10-01                       -538.0
61671            Oct-65            2065-10-01                       -562.0
62025            Oct-63            2063-10-01                       -538.0
62469            Sep-66            2066-09-01                       -573.0
62484            Sep-67            2067-09-01                       -585.0
62777            Apr-68            2068-04-01                       -592.0
63123            Aug-68            2068-08-01                       -596.0
63125            Sep-53            2053-09-01                       -417.0
64334            Aug-66            2066-08-01                       -572.0
64390            Jan-56            2056-01-01                       -445.0
65915            Feb-67            2067-02-01                       -578.0
66853            Feb-68            2068-02-01                       -590.0
66900            May-66            2066-05-01                       -569.0
67037            Feb-67            2067-02-01                       -578.0
67454            Sep-63            2063-09-01                       -537.0
67796            Nov-68            2068-11-01                       -599.0
67997            Jan-65            2065-01-01                       -553.0
68243            Nov-65            2065-11-01                       -563.0
68376            Apr-67            2067-04-01                       -580.0
69096            Mar-68            2068-03-01                       -591.0
70395            Mar-68            2068-03-01                       -591.0
70549            Jan-68            2068-01-01                       -589.0
70990            Jul-63            2063-07-01                       -535.0
71973            Nov-67            2067-11-01                       -587.0
72544            Apr-55            2055-04-01                       -436.0
72854            Sep-67            2067-09-01                       -585.0
73560            Feb-68            2068-02-01                       -590.0
74378            Oct-64            2064-10-01                       -550.0
74409            Jan-66            2066-01-01                       -565.0
74531            Jun-67            2067-06-01                       -582.0
75944            Aug-59            2059-08-01                       -488.0
76713            Jan-63            2063-01-01                       -529.0
76748            Feb-66            2066-02-01                       -566.0
76958            Jan-67            2067-01-01                       -577.0
77755            Aug-66            2066-08-01                       -572.0
77881            May-67            2067-05-01                       -581.0
78272            Mar-68            2068-03-01                       -591.0
78413            Jul-66            2066-07-01                       -571.0
79108            Sep-67            2067-09-01                       -585.0
79307            Feb-68            2068-02-01                       -590.0
79497            Jun-65            2065-06-01                       -558.0
79531            Mar-67            2067-03-01                       -579.0
79654            Oct-62            2062-10-01                       -526.0
80121            Jul-66            2066-07-01                       -571.0
80441            Feb-68            2068-02-01                       -590.0
81072            Nov-67            2067-11-01                       -587.0
81182            Sep-64            2064-09-01                       -549.0
82283            May-63            2063-05-01                       -533.0
82676            May-67            2067-05-01                       -581.0
82743            Aug-67            2067-08-01                       -584.0
83278            Aug-59            2059-08-01                       -488.0
84201            Jul-66            2066-07-01                       -571.0
85153            Jan-60            2060-01-01                       -493.0
85428            Jan-60            2060-01-01                       -493.0
85776            Mar-67            2067-03-01                       -579.0
85811            Nov-66            2066-11-01                       -575.0
86473            May-64            2064-05-01                       -545.0
86540            Oct-68            2068-10-01                       -598.0
86572            Nov-67            2067-11-01                       -587.0
86711            Jun-58            2058-06-01                       -474.0
86823            Feb-68            2068-02-01                       -590.0
87302            Jan-66            2066-01-01                       -565.0
87867            Jan-66            2066-01-01                       -565.0
87889            Dec-67            2067-12-01                       -588.0
87988            Jun-68            2068-06-01                       -594.0
89378            Nov-56            2056-11-01                       -455.0
89457            Aug-66            2066-08-01                       -572.0
89548            May-64            2064-05-01                       -545.0
89652            Feb-61            2061-02-01                       -506.0
89957            Apr-68            2068-04-01                       -592.0
89969            Apr-66            2066-04-01                       -568.0
91382            Jan-63            2063-01-01                       -529.0
91764            Jan-67            2067-01-01                       -577.0
93294            Jan-61            2061-01-01                       -505.0
93555            May-68            2068-05-01                       -593.0
93733            Aug-66            2066-08-01                       -572.0
94117            Sep-66            2066-09-01                       -573.0
94388            Jul-59            2059-07-01                       -487.0
94474            Sep-64            2064-09-01                       -549.0
94573            May-65            2065-05-01                       -557.0
95724            Mar-62            2062-03-01                       -519.0
95874            Apr-66            2066-04-01                       -568.0
96320            Sep-64            2064-09-01                       -549.0
96947            Jan-55            2055-01-01                       -433.0
96993            Feb-68            2068-02-01                       -590.0
97053            Dec-68            2068-12-01                       -600.0
97282            Apr-66            2066-04-01                       -568.0
97378            Mar-66            2066-03-01                       -567.0
97447            Sep-67            2067-09-01                       -585.0
97652            Nov-68            2068-11-01                       -599.0
97666            Jan-67            2067-01-01                       -577.0
97689            Apr-66            2066-04-01                       -568.0
97890            Jun-63            2063-06-01                       -534.0
98889            Feb-68            2068-02-01                       -590.0
99436            Mar-58            2058-03-01                       -471.0
99892            Jan-58            2058-01-01                       -469.0

In [77]:
# Es gibt 2303 solche Werte.
# Negative Werte werden durch den Maximalwert der Spalte ersetzt, da diese auf einer Fehlinterpretation des Jahres beruhen (z.B. '57' als 2057 anstatt 1957).
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

In [36]:
min(loan_data['mths_since_earliest_cr_line'])

73.0

Term